version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
